### ISSUE TITLE
ValueError: buffer is smaller than requested size

### ISSUE THREAD

**Issue by driesgouwss** [rtlsdrblog/kerberossdr#24]
serving on 0.0.0.0:8080 view at http://127.0.0.1:8080
Traceback (most recent call last):
  File "/home/enoeb/kerberossdr/_signalProcessing/hydra_signal_processor.py", line 165, in run
    self.module_receiver.download_iq_samples()
  File "/home/enoeb/kerberossdr/_receiver/hydra_receiver.py", line 161, in download_iq_samples
    byte_data_np = np.frombuffer(byte_array_read, dtype='uint8', count=read_size)
ValueError: buffer is smaller than requested size

On processing click I get this error

**Comment by MrManlu** [comment]
I have exactly the same problem. I don't know why, because it worked two days ago. I think is something related with USB 3.0 ports, but I'm not 100% sure.

I modified `hydra_receiver.py` to print the length of the buffer:
```python
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 1388, in _shutdown
Byte array length: 0 B; Requested: 1048576 B
Traceback (most recent call last):
  File "/home/kerberos/kerberossdr/_signalProcessing/hydra_signal_processor.py", line 165, in run
    lock.acquire()
KeyboardInterrupt: 
    self.module_receiver.download_iq_samples()
  File "/home/kerberos/kerberossdr/_receiver/hydra_receiver.py", line 161, in download_iq_samples
    byte_data_np = np.frombuffer(byte_array_read, dtype='uint8', count=read_size)
ValueError: buffer is smaller than requested size
```
As you can see, the Byte array length is `0` Bytes long. GUI graphs are frozen with the random initial data.

Anyone had the same problem?
